# Generated by Django 5.2.6 on 2025-10-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapendientes',
            name='titulo',
            field=models.CharField(default='Tareas pendientes', max_length=50),
        ),
    ]
