# Generated by Django 5.2.5 on 2025-10-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_alter_listapendientes_titulo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='repetir_anualmente',
            field=models.BooleanField(default=False, verbose_name='Repetir cada año'),
        ),
    ]
