# Generated by Django 5.2.6 on 2025-10-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_alter_listapendientes_titulo'),
        ('Eventos', '0003_evento_repetir_anualmente'),
    ]

    operations = [
    ]
