# Generated by Django 5.2.6 on 2025-11-12 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_perfil_confirmado_perfil_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantUsuarios', models.IntegerField()),
                ('metaCantHoras', models.IntegerField()),
                ('plazoInicioEstudio', models.DateTimeField()),
                ('plazoFinEstudio', models.DateTimeField()),
                ('idPlanificadorLider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_liderados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='Usuarios.grupoestudio'),
        ),
    ]
