# Generated by Django 5.2.6 on 2025-11-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_grupoestudio_perfil_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
