# Generated by Django 5.2.6 on 2025-11-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_perfil_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoestudio',
            name='cantUsuarios',
            field=models.IntegerField(default=0),
        ),
    ]
