# Generated by Django 5.2.6 on 2025-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_alter_grupoestudio_idplanificadorlider'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_union_grupo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
