# Generated by Django 5.2.6 on 2025-11-20 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_perfil_fecha_union_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestudio',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 20, 19, 43, 56, 804024, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
