# Generated by Django 5.2.6 on 2025-10-10 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_estudio', models.DurationField()),
                ('tiempo_descanso', models.DurationField()),
                ('repeticiones', models.IntegerField()),
                ('repeticiones_completadas', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('meta_en_minutos', models.IntegerField()),
                ('meta_minutos_alcanzados', models.IntegerField(default=0)),
                ('porcentaje_exito', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
