# Generated by Django 5.2.6 on 2025-10-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronometro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionestudio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
