# Generated by Django 5.2.6 on 2025-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronometro', '0002_sesionestudio_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionestudio',
            name='meta_minutos_alcanzados',
            field=models.FloatField(default=0.0),
        ),
    ]
