# Generated by Django 5.2.6 on 2025-11-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrousuario',
            old_name='fecha_desbloqueado',
            new_name='fecha_desbloqueo',
        ),
    ]
