# Generated by Django 5.2.6 on 2025-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensas', '0002_rename_fecha_desbloqueado_logrousuario_fecha_desbloqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrousuario',
            name='reclamado',
            field=models.BooleanField(default=False),
        ),
    ]
