# Generated by Django 5.2.6 on 2025-11-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensas', '0003_logrousuario_reclamado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logro',
            old_name='audio_url',
            new_name='recompensa_url',
        ),
        migrations.RemoveField(
            model_name='logro',
            name='img_url',
        ),
    ]
