# Generated by Django 5.2.6 on 2025-11-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensas', '0004_rename_audio_url_logro_recompensa_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='recompensa_descripcion',
            field=models.CharField(default='recompensa', max_length=30),
        ),
    ]
