# Generated by Django 5.2.6 on 2025-11-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recompensas', '0005_logro_recompensa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='recompensa_descripcion',
            field=models.CharField(max_length=30),
        ),
    ]
